# Generated by Django 6.0.6 on 2026-06-06 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome / Razão social')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=80, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=80, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=80, verbose_name='Número de série')),
                ('numero_patrimonio', models.CharField(max_length=80, unique=True, verbose_name='Número de patrimônio')),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor pago na compra')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de aquisição')),
                ('local', models.CharField(blank=True, max_length=120, verbose_name='Localização atual')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('LOCADO', 'Locado'), ('MANUTENCAO', 'Em manutenção'), ('BAIXADO', 'Baixado / Descartado')], default='DISPONIVEL', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='inventario.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da locação')),
                ('data_inicio', models.DateField(verbose_name='Início do contrato')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Término do contrato')),
                ('ativa', models.BooleanField(default=True, verbose_name='Locação ativa')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locacoes', to='inventario.cliente', verbose_name='Cliente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locacoes', to='inventario.equipamento', verbose_name='Equipamento')),
            ],
            options={
                'verbose_name': 'Locação',
                'verbose_name_plural': 'Locações',
                'ordering': ['-data_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('descricao', models.TextField(verbose_name='Descrição do serviço')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo')),
                ('tecnico', models.CharField(blank=True, max_length=120, verbose_name='Técnico responsável')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='inventario.equipamento', verbose_name='Equipamento')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CADASTRO', 'Cadastro'), ('EDICAO', 'Edição'), ('LOCAL', 'Mudança de localização'), ('STATUS', 'Mudança de status'), ('MANUTENCAO', 'Manutenção'), ('LOCACAO', 'Locação'), ('DEVOLUCAO', 'Devolução'), ('BAIXA', 'Baixa')], max_length=15, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='inventario.equipamento', verbose_name='Equipamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
