# Generated by Django 6.0.6 on 2026-06-22 02:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_contrato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Nº do aditivo')),
                ('tipo', models.CharField(choices=[('ADICAO', 'Adição'), ('REMOCAO', 'Remoção')], max_length=10, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, help_text='Ex.: Computador Dell, Monitor 24"...', max_length=200, verbose_name='Item / descrição')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor unitário')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data do aditivo')),
                ('arquivo', models.FileField(blank=True, upload_to='aditivos/%Y/', verbose_name='PDF do aditivo (opcional)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='inventario.contrato', verbose_name='Contrato')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Aditivo',
                'verbose_name_plural': 'Aditivos',
                'ordering': ['contrato', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('contrato', 'numero'), name='aditivo_numero_unico_por_contrato')],
            },
        ),
    ]
