# Generated by Django 6.0.6 on 2026-06-22 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_aditivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locacoes', to='inventario.contrato', verbose_name='Contrato'),
        ),
    ]
