# Generated by Django 6.0.6 on 2026-06-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_locacao_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='arquivo',
            field=models.FileField(blank=True, upload_to='contratos/%Y/', verbose_name='Arquivo (PDF)'),
        ),
    ]
