# Generated by Django 6.0.6 on 2026-06-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_contrato_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aditivo',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='aditivo',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='aditivo',
            name='valor_unitario',
        ),
        migrations.AddField(
            model_name='aditivo',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Apenas registro; não muda o valor do contrato.', max_digits=12, null=True, verbose_name='Valor de referência'),
        ),
        migrations.AlterField(
            model_name='aditivo',
            name='descricao',
            field=models.CharField(help_text='Ex.: "Adição de 3 notebooks", "Remoção de 1 máquina"...', max_length=200, verbose_name='Descrição da alteração'),
        ),
    ]
