# Generated by Django 6.0.6 on 2026-06-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_aditivo_quantidade_remove_aditivo_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aditivo',
            name='tipo',
            field=models.CharField(choices=[('ADICAO', 'Adição'), ('REMOCAO', 'Remoção')], default='ADICAO', max_length=10, verbose_name='Tipo de alteração'),
        ),
        migrations.AlterField(
            model_name='aditivo',
            name='descricao',
            field=models.CharField(help_text='Ex.: "Notebook Lenovo (Pat. 8974)", "1 máquina removida"...', max_length=200, verbose_name='Equipamento / descrição'),
        ),
        migrations.AlterField(
            model_name='aditivo',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço do equipamento desta alteração. Apenas registro — não muda o valor do contrato.', max_digits=12, null=True, verbose_name='Valor do equipamento'),
        ),
    ]
