# Generated by Django 6.0.6 on 2026-08-09 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_aditivo_tipo_alter_aditivo_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Nome do produto')),
                ('ordem', models.PositiveIntegerField(default=100, help_text='Menor aparece primeiro. Produtos novos entram no fim.', verbose_name='Ordem de exibição')),
                ('pede_configuracao', models.BooleanField(default=False, help_text='Marque para produtos como Desktop e Notebook, que precisam desses três campos a mais no cadastro.', verbose_name='Pede configuração (processador / RAM / armazenamento)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='equipamento',
            name='armazenamento',
            field=models.CharField(blank=True, max_length=60, verbose_name='Armazenamento (SSD/HD)'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='memoria_ram',
            field=models.CharField(blank=True, max_length=60, verbose_name='Memória RAM'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='processador',
            field=models.CharField(blank=True, max_length=120, verbose_name='Processador'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='inventario.produto', verbose_name='Produto'),
        ),
    ]
