# Generated by Django 6.0.6 on 2026-09-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_produtos_iniciais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['-data_contrato', '-id'], 'permissions': [('ver_contratos', 'Pode ver a aba de Contratos'), ('ver_pdfs', 'Pode abrir os PDFs anexados')], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
    ]
