# Generated by Django 6.0.6 on 2026-09-09 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_contrato_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Descreva o problema ou o serviço pedido.', verbose_name='O que deve ser feito')),
                ('solicitante', models.CharField(blank=True, help_text='Nome de quem procurou a recepção (opcional).', max_length=120, verbose_name='Quem pediu')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('ENCERRADO', 'Encerrado')], default='ABERTO', max_length=10, verbose_name='Status')),
                ('aberto_em', models.DateTimeField(auto_now_add=True, verbose_name='Aberto em')),
                ('realizado', models.TextField(blank=True, verbose_name='O que foi realizado')),
                ('encerrado_em', models.DateTimeField(blank=True, null=True, verbose_name='Encerrado em')),
                ('aberto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_abertos', to=settings.AUTH_USER_MODEL, verbose_name='Aberto por')),
                ('encerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_encerrados', to=settings.AUTH_USER_MODEL, verbose_name='Encerrado por')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='inventario.equipamento', verbose_name='Máquina')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_designados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico designado')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-aberto_em', '-id'],
            },
        ),
    ]
