# Generated by Django 6.0.6 on 2026-09-09 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_chamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='inventario.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('URGENTE', 'Urgente'), ('NORMAL', 'Normal'), ('LEVE', 'Leve')], default='NORMAL', help_text='Urgente = parou o trabalho · Normal = do dia · Leve = pode esperar.', max_length=10, verbose_name='Urgência'),
        ),
    ]
