# Generated by Django 6.0.6 on 2026-09-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_produto_tablet'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='arquivo_os',
            field=models.FileField(blank=True, upload_to='ordens_servico/%Y/', verbose_name='OS digitalizada (PDF ou imagem)'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='houve_troca_peca',
            field=models.BooleanField(default=False, verbose_name='Houve troca de peça?'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações do atendimento'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='peca_substituida',
            field=models.CharField(blank=True, help_text='Ex.: "Fonte 500W", "Toner preto", "SSD 240 GB".', max_length=200, verbose_name='Peça substituída'),
        ),
    ]
