# Generated by Django 6.0.6 on 2026-09-18 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_chamado_arquivo_os_chamado_houve_troca_peca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='aditivo',
            field=models.ForeignKey(blank=True, help_text='Aditivo que incluiu esta máquina no contrato, quando veio por um.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locacoes', to='inventario.aditivo', verbose_name='Aditivo'),
        ),
    ]
