# Generated by Django 6.0.6 on 2026-09-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_locacao_aditivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aditivo',
            name='descricao',
            field=models.CharField(help_text='Ex.: "Notebook Lenovo (INF-8974)", "1 máquina removida"...', max_length=200, verbose_name='Equipamento / descrição'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='numero_patrimonio',
            field=models.CharField(help_text='Número da etiqueta INF colada no equipamento.', max_length=80, unique=True, verbose_name='INF'),
        ),
    ]
