# Generated by Django 6.0.6 on 2026-09-22 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_alter_aditivo_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aditivo',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço do equipamento desta alteração. Apenas registro — não muda o valor do contrato.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0, message='Não pode ser negativo.')], verbose_name='Valor do equipamento'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0, message='Não pode ser negativo.')], verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='valor_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0, message='Não pode ser negativo.')], verbose_name='Valor pago na compra'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Não pode ser negativo.')], verbose_name='Valor da locação'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0, message='Não pode ser negativo.')], verbose_name='Custo'),
        ),
    ]
