"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Em produção, defina a variável de ambiente DJANGO_SECRET_KEY (ex.: no
# arquivo WSGI do PythonAnywhere) em vez de usar o valor padrão abaixo.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-tzodf7v9s6%^kid6h%i51#zlcrm%$rwwk0r@yt1lopey1&qxyk',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defina DJANGO_DEBUG=False em produção.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Em produção, defina DJANGO_ALLOWED_HOSTS com os hosts separados por vírgula,
# ex.: "suaempresa.pythonanywhere.com,stocklink.suaempresa.com.br"
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventario',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Localmente continua usando SQLite (nenhuma variável de ambiente definida).
# Em produção (VPS), defina DB_ENGINE=postgresql + DB_NAME/DB_USER/DB_PASSWORD
# para usar PostgreSQL, que suporta múltiplos usuários gravando ao mesmo tempo.

if os.environ.get('DB_ENGINE') == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['DB_NAME'],
            'USER': os.environ['DB_USER'],
            'PASSWORD': os.environ['DB_PASSWORD'],
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                # WAL permite leituras e escritas simultâneas sem travar o
                # banco inteiro; timeout maior evita erro "database is
                # locked" quando várias pessoas usam o sistema ao mesmo tempo.
                'init_command': 'PRAGMA journal_mode=wal; PRAGMA synchronous=NORMAL;',
                'timeout': 20,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Maceio'

USE_I18N = True

USE_TZ = True

# Mostra valores com separador de milhar no padrão pt-br (ex.: 15.000,00)
USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Pasta onde `collectstatic` reúne os arquivos estáticos para produção
# (necessário para o mapeamento de static files no PythonAnywhere).
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Arquivos enviados pelos usuários (ex.: PDFs de contratos)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Autenticação
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'equipamento_lista'
LOGOUT_REDIRECT_URL = 'login'

# Mensagens: Bootstrap usa 'danger' no lugar de 'error'
from django.contrib.messages import constants as messages_constants  # noqa: E402

MESSAGE_TAGS = {messages_constants.ERROR: 'danger'}
