"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Modo de desenvolvimento x produção
# ----------------------------------
# O padrão é PRODUÇÃO (DEBUG desligado). Esquecer uma variável de ambiente no
# servidor tem que deixar o site fechado, nunca aberto: com DEBUG ligado, um
# erro qualquer mostra código, caminhos e dados da requisição para quem
# estiver do outro lado.
#
# No computador de desenvolvimento quem liga o DEBUG é o `manage.py`
# (DJANGO_DEBUG=True por padrão), então o `runserver` continua funcionando
# sem configurar nada. O site em produção entra pelo arquivo WSGI, que não
# passa pelo `manage.py` — lá o DEBUG fica desligado a menos que alguém
# defina DJANGO_DEBUG=True de propósito.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# A chave assina sessões e links de redefinição de senha: quem a conhece
# consegue se passar por qualquer usuário. Em produção ela SÓ pode vir da
# variável de ambiente DJANGO_SECRET_KEY (no arquivo WSGI do PythonAnywhere);
# sem ela o site se recusa a subir. A chave fixa abaixo serve só para
# desenvolvimento e não vale nada fora dele.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured(
            'Defina a variável de ambiente DJANGO_SECRET_KEY (produção) ou '
            'DJANGO_DEBUG=True (desenvolvimento).'
        )
    SECRET_KEY = 'django-insecure-somente-desenvolvimento-nao-usar-em-producao'

# Em produção, defina DJANGO_ALLOWED_HOSTS com os hosts separados por vírgula,
# ex.: "suaempresa.pythonanywhere.com,stocklink.suaempresa.com.br"
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if h.strip()
]

# HTTPS em produção
# -----------------
# No PythonAnywhere o HTTPS termina no proxy da frente, que repassa a
# requisição ao Django por HTTP e avisa no cabeçalho X-Forwarded-Proto se o
# navegador usou https. Sem ler esse cabeçalho o Django acharia que tudo é
# HTTP e não mandaria o HSTS.
#
# O redirecionamento de http:// para https:// NÃO é feito aqui
# (SECURE_SSL_REDIRECT): quem faz é a opção "Force HTTPS" da aba Web do
# PythonAnywhere. Se o cabeçalho acima deixasse de chegar, o redirect pelo
# Django viraria um laço infinito e derrubaria o site.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Cookies de sessão e CSRF só trafegam por https: numa rede Wi-Fi
    # aberta, ninguém copia a sessão de quem está logado.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS: o navegador passa a recusar http:// para este site pelo tempo
    # definido. Começa em 1 hora; depois de confirmar que tudo funciona em
    # https, dá para subir (ex.: DJANGO_HSTS_SECONDS=31536000, um ano).
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', '3600'))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventario',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'inventario.context_processors.permissoes',
                'inventario.context_processors.identidade',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Localmente continua usando SQLite (nenhuma variável de ambiente definida).
# Em produção (VPS), defina DB_ENGINE=postgresql + DB_NAME/DB_USER/DB_PASSWORD
# para usar PostgreSQL, que suporta múltiplos usuários gravando ao mesmo tempo.

if os.environ.get('DB_ENGINE') == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['DB_NAME'],
            'USER': os.environ['DB_USER'],
            'PASSWORD': os.environ['DB_PASSWORD'],
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                # timeout maior evita erro "database is locked" quando várias
                # pessoas usam o sistema ao mesmo tempo. O modo WAL em si é
                # ativado via signal em inventario/apps.py (mais compatível
                # entre versões do que a opção 'init_command').
                'timeout': 20,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Maceio'

USE_I18N = True

USE_TZ = True

# Mostra valores com separador de milhar no padrão pt-br (ex.: 15.000,00)
USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Pasta onde `collectstatic` reúne os arquivos estáticos para produção
# (necessário para o mapeamento de static files no PythonAnywhere).
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Arquivos enviados pelos usuários (ex.: PDFs de contratos)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Identidade que aparece nas telas e nos papéis
# ----------------------------------------------
# O nome TÉCNICO do sistema continua StockLink: o repositório, a pasta, o
# endereço do site e o banco não mudam. O que está aqui é só o que a equipe
# e o cliente leem na tela e na folha impressa.
#
# Trocou o nome da empresa? Muda aqui, em um lugar só — nenhum template
# repete esse texto.
NOME_SISTEMA = 'INFORLINK'
NOME_EMPRESA = 'INFORLINK INOVAÇÕES EM TECNOLOGIA'

# Analista: o único usuário que define perfis e libera áreas restritas
# (ver inventario/permissoes.py). É o login do Márlon.
USUARIO_ANALISTA = 'admin'

# Autenticação
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'equipamento_lista'
LOGOUT_REDIRECT_URL = 'login'

# Mensagens: Bootstrap usa 'danger' no lugar de 'error'
from django.contrib.messages import constants as messages_constants  # noqa: E402

MESSAGE_TAGS = {messages_constants.ERROR: 'danger'}
